[theme]
primaryColor = "#aad3a8"           # Accent color for widgets
backgroundColor = "#aad3a8"        # Main background color
secondaryBackgroundColor = "#28707c"  # Sidebar and widget background
textColor = "#fff"              # Text color
font = "sans serif"                # Font family: "sans serif", "serif", or "monospace"
